#import "statements.typ": remark, theorem
#import "main-defs.typ": bib-ref, eq, res, source

#source(151, "139")
Estimation with respect to several parameters is one of the more difficult
problems in asymptotic analysis; see the surveys #bib-ref(
  "Kolchin1976",
  "Good1957",
  "Subkhankulov1976",
) and the articles #bib-ref("Malyshev1973", "Ivchenko1965a"). Good #bib-ref(
  "Good1957",
) gave a general scheme for coefficients of large powers, with the analytic
conditions to be justified in each application; see also the one-variable case
in #bib-ref("Sevastyanov1964"). The following form makes the conditions for a
uniform Gaussian estimate explicit.

#theorem[
  _Let $x=(x_1,dots,x_n)$, $r=(r_1,dots,r_n)$, and $M=(M_1,dots,M_n)$. Suppose
  that the Laurent series_
  #eq(
    $
      f(x)=sum_(r_1=-infinity)^infinity dots
      sum_(r_n=-infinity)^infinity a(r)x^r
    $,
  ) <eq:good-laurent-series>
  _has nonnegative coefficients, not all zero, and a nonempty open domain $D$ of
  absolute convergence in $(CC without {0})^n$. Fix signs $epsilon_j in {-1,1}$
  and assume:_

  _(\*) There are positive integers $R_(10),dots,R_(n 0)$ such that every
  integer vector $R$ satisfying $epsilon_j R_j>R_(j 0)$ for all $j$ is a finite
  sum, with positive integer multiplicities, of vectors $r$ for which $a(r)>0$._

  _Assume also that the integer group generated by all support differences
  $r-r'$ with $a(r)a(r')>0$ is $ZZ^n$. For a positive integer $t$, define_
  #eq(
    $
      c(M;t)=res_(x_1 dots x_n) f(x)^t
      x_1^(-M_1-1) dots x_n^(-M_n-1).
    $,
  ) <eq:good-power-coefficient>
  _Consider classes of integer vectors $M$ such that_
  #eq($ |M_j/t|+|t/M_j|<=C, quad j=1,dots,n, $) <eq:good-ratio-bound>
  _with a constant $C$ independent of $M,t$,_
  #eq($ op("sgn") M_j=epsilon_j, quad j=1,dots,n, $) <eq:good-sign-condition>
  _and, for every vector in these classes and all sufficiently large $t$,_
  #eq($ c(M;t)>0. $) <eq:good-coefficient-positivity>

  _There is at most one positive real vector $rho in D$ satisfying_
  #eq(
    $
      t rho_j frac(partial f(rho), partial rho_j)=M_j f(rho),
      quad j=1,dots,n.
    $,
  ) <eq:good-saddle-system>
  _If these solutions exist and remain in a fixed compact subset of
  $D ∩ (0,infinity)^n$, then, uniformly over the chosen classes as
  $t arrow.r infinity$,_
  #eq(
    $
      c(M;t) ∼ frac(
        f(rho)^t,
        (2pi t)^(n/2)rho_1^(M_1) dots rho_n^(M_n)sqrt(Delta)
      ),
    $,
  ) <eq:good-asymptotic>
  _where_
  #eq($ Delta=det lr([k^(j k)(rho)])>0, $) <eq:good-hessian-determinant>
  #source(152, "140")
  #eq(
    $
      k^(j k)(rho)=rho_j frac(partial, partial rho_j)
      lr((rho_k frac(partial, partial rho_k)log f(rho))),
    $,
  ) <eq:good-logarithmic-hessian>
  _including $j=k$. Equivalently,_
  #eq(
    $
      k^(j k)(rho)=lr(
        [frac(
            partial^2,
            partial xi_j partial xi_k
          )log f(e^(xi_1),dots,e^(xi_n))]
      )
      bar_(xi=log rho).
    $,
  ) <eq:good-exponential-hessian>
] <th:good-laurent-series>

To see the role of these conditions, put $p_r=a(r)rho^r/f(rho)$. These positive
support weights sum to one, and the gradient and Hessian of $log f(e^xi)$ are
the mean vector and covariance matrix of $r$ under these weights. The support
differences span $RR^n$, so every nonzero real projection of $r$ has positive
variance. Thus the Hessian is positive definite. The logarithmic domain of
convergence is convex, and strict convexity gives uniqueness in
@eq:good-saddle-system.

On the torus $x_j=rho_j e^(i theta_j)$, equality in $|f(x)|<=f(rho)$ requires
all supported monomials to have the same phase. The full integer lattice of
support differences makes $theta=0$ the only such point modulo $2pi$. Away from
it the modulus is uniformly smaller; near it the logarithm has quadratic term
$-frac(1, 2)theta^T k(rho)theta$. Compactness of the saddle vectors gives
uniform derivative bounds and a uniform positive lower bound for the covariance
eigenvalues. Cauchy's coefficient integral then reduces to the Gaussian
integral, yielding @eq:good-asymptotic.

#remark[
  Condition (\*) concerns unrestricted sums of support vectors; fixed powers
  also require attention to periodicity. In one variable, a support contained in
  $a+d ZZ$ can be reduced by extracting $x^a$ and using $x^d$ as the new
  variable, while retaining the restriction $M equiv a t mod d$. A single
  supported exponent gives a monomial and no nondegenerate Gaussian estimate.
  The compactness condition is separate: bounded ratios in @eq:good-ratio-bound
  alone do not prevent a saddle from approaching a boundary.

  Good #bib-ref("Good1957"), Theorem 6.2, gives further terms in two variables;
  see @th:bipartite-coloring-residue.
]
