#import "main-defs.typ": bib-ref, eq, res, source
#import "statements.typ": corollary, lemma, proof, theorem
#import "book-style.typ": keep-next, keep-together

#source(227, "215")
#heading(level: 2, numbering: (..n) => "§" + numbering("1.", ..n))[
  The ranks of the factors for the $p$-central series of free groups in
  varieties
] <sec:p-central-ranks>

Let $p$ be a prime. The _lower $p$-central series_ of a group $G$ is
$
  G_1=G, quad G_(i+1)=[G_i,G] G_i^p, quad i>=1.
$
Here $H^r$ denotes the subgroup generated by the $r$th powers of elements of
$H$. Stabilization of this series at a term of finite index is related to the
restricted Burnside problem. Its factors are studied in #bib-ref("Skopin1950")
and #bib-ref("Skopin1965").

In @sec:solvable-polynilpotent-ranks we found the ranks of the lower central
factors of free solvable and polynilpotent groups. We now find bases for their
$p$-central factors, and then obtain rank recurrences by summation. We give the
resulting formulas for free solvable groups; the polynilpotent case can be
treated in the same way.

Throughout this section, $[a,b]=a^(-1)b^(-1)a b$, and longer commutators are
associated to the left. Products of noncommuting elements are taken in the
indicated order.

#lemma[
  _Let $G$ be any group, let $a,f_1,dots,f_s in G$, and let $s,t>=1$. Then there
  are finite ordered index sets $H_j$ such that_
  #eq(
    $
      [a^(p^t),f_1,dots,f_s]=[a,f_1,dots,f_s]^(p^t)
      product_(j=1)^t product_(i in H_j)
      [a,f_1^((i)),dots,f_(s(i))^((i))]^(p^(t-j)),
    $,
  ) <eq:power-commutator-collection>
  _where $s(i)>=s+j$ for $i in H_j$, and the $f_l^((i))$ are elements of $G$._
] <lem:power-commutator-collection>

#source(228, "216")
#proof[
  For $t=0$ the assertion is immediate, with an empty product. Assume it holds
  for every $s$ and all $t<=m$. Put $C=[a,f_1,dots,f_s]$. Collecting a $p$th
  power first gives
  $
    [a^(p^(m+1)),f_1,dots,f_s]
    =[a^(p^m),f_1,dots,f_s]^p
    product_ν [a^(p^m),g_(ν,1),dots,g_(ν,r_ν)],
  $
  where $r_ν>=s+1$. Apply the induction hypothesis separately to each factor.
  Writing $D_ν=[a,g_(ν,1),dots,g_(ν,r_ν)]$, we obtain #eq(
    $
      [a^(p^(m+1)),f_1,dots,f_s]
      =lr((C^(p^m) product_(j=1)^m U_j))^p
      product_ν lr((D_ν^(p^m) product_(j=1)^m V_(ν,j))).
    $,
  ) <eq:power-commutator-induction>
  Here $U_j$ is a product of $p^(m-j)$th powers of commutators beginning with
  $a$ and having at least $s+j$ further entries. The corresponding factors in
  $V_(ν,j)$ have at least $r_ν+j$ further entries.

  Collect the copies of $C$, then the factors at each successive power level.
  Interchanging two factors introduces commutators with an additional entry;
  these are placed at a later level. Reapply the induction hypothesis to any
  powered entry. After the $m+1$ power levels have been treated, all remaining
  factors have at least $s+m+1$ further entries and require no power extraction.
  This finite collection gives @eq:power-commutator-collection.
]

#theorem[
  _For a free group $F$ and every $m>=1$,_
  $
    F_m=product_(i=0)^(m-1) γ_(m-i)(F)^(p^i).
  $
] <th:p-central-product-formula>

#proof[
  The cases $m=1,2$ follow from the definition. Assume the formula holds through
  $m$. Write $γ_j=γ_j (F)$. Then
  $
    F_(m+1)=F_m^p [F_m,F],
  $
  and #eq(
    $
      [F_m,F]=[γ_m γ_(m-1)^p dots γ_1^(p^(m-1)),F].
    $,
  ) <eq:p-central-commutator-layer>
  The subgroup on the left is generated by commutators $[a b,c]$ with
  $a in γ_m$, $b in γ_(m-1)^p dots γ_1^(p^(m-1))$, and $c in F$. The identity
  $
    [a b,c]=[a,c][a,c,b][b,c]
  $
  and normality of the subgroups imply
  $
    [F_m,F]=γ_(m+1)[γ_(m-1)^p dots γ_1^(p^(m-1)),F].
  $

  #source(229, "217")
  Repeating this argument separates all the factors:
  $
    [F_m,F]=γ_(m+1) product_(i=1)^(m-1)[γ_(m-i)^(p^i),F].
  $
  #keep-next[
    For $a_1,dots,a_r in γ_(m-1)$, @lem:power-commutator-collection gives
  ]
  #eq(
    $
      [a_1^p dots a_r^p,f]
      equiv [a_1,f]^p dots [a_r,f]^p quad (mod γ_(m+1)).
    $,
  ) <eq:power-product-congruence>
  Thus #eq(
    $
      γ_(m+1)γ_m^p supset.eq γ_(m+1)[γ_(m-1)^p,F].
    $,
  ) <eq:p-central-first-inclusion>
  Conversely,
  $
    [f_1,dots,f_m]^p
    equiv [[f_1,dots,f_(m-1)]^p,f_m] quad (mod γ_(m+1)),
  $
  so @eq:p-central-first-inclusion is an equality. This replaces the first
  commutator subgroup by $γ_m^p$.

  For the general step, put
  $
    U_i=product_(j=0)^(i-1)γ_(m+1-j)^(p^j), quad 1<=i<=m-1.
  $
  Suppose the factors with smaller power indices have already been treated. A
  generating commutator for $[γ_(m-i)^(p^i),F]$ has the form $[b_1 dots b_r,f]$,
  where $b_j=a_j^(p^i)$ and $a_j in γ_(m-i)$. Let $B_j=b_(j+1) dots b_r$, with
  $B_r=1$. Repeated use of the product identity gives the exact equality #eq(
    $
      [b_1 dots b_r,f]=product_(j=1)^r lr(([b_j,f][b_j,f,B_j])).
    $,
  ) <eq:product-commutator-expansion>
  @lem:power-commutator-collection puts each factor in $U_i γ_(m-i+1)^(p^i)$,
  and hence #eq(
    $
      U_i [γ_(m-i)^(p^i),F] subset.eq U_i γ_(m-i+1)^(p^i).
    $,
  ) <eq:p-central-layer-inclusion>
  For the reverse inclusion, apply the lemma to a commutator of length
  $h=m+1-i$:
  $
    [x_1,dots,x_h]^(p^i)
    equiv [[x_1,dots,x_(h-1)]^(p^i),x_h] quad (mod U_i).
  $
  Such commutators generate $γ_h$ modulo the higher terms already in $U_i$.
  Induction on $i$ therefore gives
  $
    [F_m,F]=product_(i=0)^(m-1)γ_(m+1-i)^(p^i).
  $

  #source(230, "218")
  It remains to collect $F_m^p$. Write
  $
    x=x_m dots x_1, quad x_j in γ_j^(p^(m-j)),
  $
  #keep-next[and set]
  $
    V_l=product_(j=0)^l γ_(m+1-j)^(p^j), quad 0<=l<=m.
  $
  Since $γ_m$ is central modulo $γ_(m+1)$,
  $
    x^p equiv (x_(m-1) dots x_1)^p quad (mod V_1).
  $
  Assume that, for some $1<=l<m$, #eq(
    $
      x^p equiv (x_(m-l) dots x_1)^p quad (mod V_l).
    $,
  ) <eq:p-central-power-truncation>
  The commutator calculation above shows that $[γ_(m-l)^(p^l),F] subset.eq V_l$.
  We may therefore collect the copies of $x_(m-l)$ to get #eq(
    $
      x^p equiv x_(m-l)^p (x_(m-l-1) dots x_1)^p quad (mod V_l).
    $,
  ) <eq:p-central-power-separation>
  Write $x_(m-l)=a_1^(p^l) dots a_s^(p^l)$ with $a_j in γ_(m-l)$. These powered
  factors commute modulo $V_l$, so
  $
    x_(m-l)^p equiv a_1^(p^(l+1)) dots a_s^(p^(l+1)) quad (mod V_l).
  $
  Consequently $x_(m-l)^p in V_(l+1)$, and @eq:p-central-power-truncation holds
  with $l+1$ in place of $l$. At the last step the remaining product is empty.
  Thus
  $
    F_m^p subset.eq V_m=product_(i=0)^m γ_(m+1-i)^(p^i),
  $
  and the same inclusion holds for $F_(m+1)$. Conversely,
  $γ_(m+1)=[γ_m,F] subset.eq [F_m,F]$, and each other factor is generated by
  $p$th powers of elements of the corresponding factor of $F_m$. This proves the
  reverse inclusion and the theorem.
]

#lemma[
  _For $0<=i<m$, the subgroup $γ_(m-i)(F)^(p^i)$ is generated modulo_
  $
    u_i=γ_(m+1)(F) product_(j=0)^(i-1) γ_(m-j)(F)^(p^j)
  $
  _by the $p^i$th powers of basic commutators of weight $m-i$. In particular,
  $u_0=γ_(m+1)(F)$._
] <lem:hall-power-generators>

#source(231, "219")
#proof[
  Modulo $γ_(m+1)(F)$, write an element $f in γ_(m-i)(F)$ in collected form as
  $f=c_1^(ε_1) dots c_t^(ε_t)$, with basic commutators $c_s$ of weights between
  $m-i$ and $m$. Collecting successive $p$th powers gives #eq(
    $
      f^(p^i) equiv
      lr((product_(s=1)^t c_s^(ε_s p^i)))
      product_(j=1)^i product_ν d_(j,ν)^(e_(j,ν)p^(i-j))
      quad (mod γ_(m+1)(F)),
    $,
  ) <eq:hall-power-expansion>
  where each $d_(j,ν)$ is a basic commutator of weight at least $m-i+j$. All
  exponents $ε_s,e_(j,ν)$ are integers. Each loss of a factor $p$ in an exponent
  is accompanied by an increase in commutator weight. Thus every factor in the
  second product belongs to $u_i$. The factors in the first product whose
  weights exceed $m-i$ also belong to $u_i$. This proves the lemma, including
  the case $i=0$.

  We will also use the corresponding divisibility statement for collected
  coordinates. Modulo $γ_(m+1)(F)$, an element of $F_m$ has each weight $w$
  coordinate divisible by $p^(m-w)$, for $1<=w<=m$. To see this, collect the
  product in @th:p-central-product-formula in order of increasing weight, using
  the same power collection as in @eq:hall-power-expansion. The original factors
  satisfy the required divisibility, and every correction term increases weight
  by at least the number of powers of $p$ lost from its exponent. This preserves
  the divisibility at every subsequent weight.

  Let $M_w$ be the set of basic commutators of weight $w$, and write
  $M_w^(p^i)=lr({c^(p^i):c in M_w})$.
]

#theorem[
  _For a free group $F$, the images of_
  $
    cal(M)_n=union_(i=0)^(n-1) M_(n-i)^(p^i)
  $
  _form a basis of the vector space $F_n/F_(n+1)$ over $bb(F)_p$._
] <th:p-central-hall-basis>

#proof[
  The factor is abelian of exponent $p$. Generation follows from
  @th:p-central-product-formula and @lem:hall-power-generators, successively
  removing factors in order of decreasing power index.

  For independence, list the basic commutators $c$ of weights at most $n$ in
  their collection order. Suppose
  $
    product_c c^(α_c p^(n-w(c))) in F_(n+1), quad 0<=α_c<p,
  $
  with at least one $α_c!=0$. This product is already in collected order.

  #source(232, "220")
  The divisibility statement for $F_(n+1)$ gives another collected
  representation #eq(
    $
      product_c c^(α_c p^(n-w(c)))
      equiv product_c c^(β_c p^(n+1-w(c)))
      quad (mod γ_(n+1)(F)),
    $,
  ) <eq:hall-coordinate-congruence>
  where $β_c$ are integers. Uniqueness of the basic-commutator coordinates
  (#bib-ref("Hall1959")) implies $α_c=p β_c$ for every $c$. This contradicts the
  choice of the $α_c$, and proves independence.
]

#corollary[
  _The same conclusion holds for a torsion-free relatively free group whose
  lower central factors have free abelian bases chosen from basic commutators,
  with the corresponding collection process._
]

Indeed, the proof uses the collection process and the free abelian basis at each
successive weight. These give unique collected coordinates in every finite
nilpotent quotient, and the same divisibility argument applies.

#corollary[
  _For such a group $G$ of finite rank,_
  $
    dim_(bb(F)_p) (G_n/G_(n+1))
    =sum_(i=1)^n op("rank")_(bb(Z))(γ_i (G)/γ_(i+1)(G)).
  $
]

Apply this result to the bases in @sec:solvable-polynilpotent-ranks. Denote by
$tilde(R)_q^((k))(n)$ the rank of the weight $n$ factor of the $p$-central
series of a free solvable group of derived length $k$ on $q>=2$ generators.
Suppress the subscript $q$ when no confusion can arise. Then
$
  tilde(R)^((k))(n)=sum_(j=1)^n R^((k))(j), quad n>=1,
$
and set $tilde(R)^((k))(n)=0$ for $n<=0$.

#theorem[
  _The initial values are_
  #eq(
    $
      tilde(R)^((2))(n)=cases(
        0 & quad n<=0,
        q & quad n=1,
        1+q+(n-1-n/q) binom(n+q-1, n) & quad n>=2.
      )
    $,
  ) <eq:p-metabelian-rank>
  _For $k>=2$, the ranks $tilde(R)^((k+1))(n)$ and $tilde(R)^((k))(n)$ are equal
  when $n<n^((k))$, where $n^((k))$ is given by @eq:derived-word-residue. For
  $n>=n^((k))$,_
  #eq(
    $
      tilde(R)^((k+1))(n) & =tilde(R)^((k))(n)+1 \
                          & +res_z lr(
                              (
                                frac(q z-1, 1-z)
                                product_(j=1)^n (1-z^j)^(
                                -tilde(R)^((k))(j)
                                +tilde(R)^((k))(j-1)
                                )
                                z^(-n-1)
                              )
                            ).
    $,
  ) <eq:p-solvable-rank-residue>


  #source(233, "221")
  _Equivalently, for $n>=n^((k))$,_
  #eq(
    $
      tilde(R)^((k+1))(n)&=tilde(R)^((k))(n)+1 \
      &+q sum_1 product_(i=1)^s binom(tilde(Q)^((k))(r_i)+k_i-1, k_i)
      \ &-sum_2 product_(i=1)^s binom(tilde(Q)^((k))(r_i)+k_i-1, k_i),
    $,
  ) <eq:p-solvable-rank-partitions>
  _where_
  #eq(
    $
      tilde(Q)^((k))(j)=cases(
        q+1 & quad j=1,
        tilde(R)^((k))(j)-tilde(R)^((k))(j-1) & quad j>=2.
      )
    $,
  ) <eq:p-solvable-rank-increments>
  _The sums $sum_1$ and $sum_2$ range over partitions of $n-1$ and $n$,
  respectively, written with distinct positive parts $r_1<dots<r_s$ and positive
  multiplicities $k_i$. The empty partition contributes $1$; a factor with zero
  colours and positive multiplicity contributes $0$._
] <th:p-metabelian-rank>

#proof[
  Summing @eq:hall-product-coefficient gives @eq:p-metabelian-rank. To sum the
  increment in @eq:solvable-rank-residue, put
  $
    P_k (z)=product_(j>=1)(1-z^j)^(-R^((k))(j)).
  $
  The series $1+(q z-1)P_k (z)$ has constant coefficient zero and positive
  coefficients $α^k (n)$. Its cumulative coefficients are therefore obtained
  from
  $
    frac(1+(q z-1)P_k (z), 1-z).
  $
  This proves @eq:p-solvable-rank-residue. Finally,
  $
    frac(P_k (z), 1-z)=product_(j>=1)(1-z^j)^(-tilde(Q)^((k))(j)),
  $
  whose binomial expansion gives
  @eq:p-solvable-rank-partitions–@eq:p-solvable-rank-increments.
]
