#import "index-style.typ": index-mark
#import "main-defs.typ": bib-ref, eq, res, source
#import "statements.typ": problem, remark, subproblem
#import "book-style.typ": keep-next

#source(235, "223")
#heading(level: 1)[Open Problems] <ch:open-problems>

In conclusion we draw the reader's attention to some open problems which, in our
view, are of interest for function theory and combinatorial analysis.

In @ch:integral-method[Chapter] the method of integral representation of sums
was constructed, using power series, as a method for finding integral
representations of combinatorial sums and evaluating them. It was justified by
the theory of one-dimensional and multiple residues, and some applications were
given in Chapters @ch:univariate-sums–@ch:applications.

It is natural to extend the method to generating functions and integrals of
other types, following the same scheme and seeking further applications. We
formulate some problems.

#problem(base-level: 1, prefix: ())[
  Construct a method of integral representation of sums according to the scheme
  of @ch:integral-method[Chapter] for generating functions
  $A(z)=sum_(n=0)^infinity a_n phi_n (z)$ defined, for example, by the following
  sequences of functions.
] <prob:generalized-series-method>

#subproblem[
  $
    phi_n (z)=z^n/((z-1)(z-2) dots (z-n)), quad n=1,2,dots, quad phi_0 (z)=1
  $
  #bib-ref("Carlitz1973b").
] <prob:factorial-rational-series>

#subproblem[
  Euler series of power type #bib-ref("Goldman1970"),
  $
    phi_n (z)=z^n/((1-q)(1-q^2) dots (1-q^n)), quad n=0,1,2,dots,
  $
  where the empty product is $1$ and $q^j != 1$ for all $j>=1$.
] <prob:q-power-series>

#subproblem[
  Interpolation series, especially series in generalized powers,
  $
    phi_n (z)=(z(z-1) dots (z-n+1))/(n!), quad n=0,1,2,dots,
  $
  with $phi_0 (z)=1$.
] <prob:interpolation-series>

#subproblem[
  Dirichlet series.

  #source(236, "224")
] <prob:dirichlet-series>

#subproblem[
  Fourier series with an orthonormal system $\{phi_n (z)\}_(n=0)^infinity$,
  especially trigonometric series and orthonormal systems of polynomials.
] <prob:fourier-series>

#subproblem[
  Other series (see #bib-ref("Doubilet1972b") and
  §@sec:rota-generating-functions).

  In these constructions, obtain analogues of the Bürmann–Lagrange series for
  inverting an implicitly defined function, whenever this operation is
  admissible in the algebra of series under consideration. Justify the
  constructions by methods of function theory.
] <prob:incidence-algebra-series>

#problem(base-level: 1, prefix: ())[
  Construct a multidimensional method for the series listed in
  @prob:generalized-series-method, following the scheme of
  @ch:integral-method[Chapter] and using multidimensional residues. Find
  inversion formulas for systems of implicitly defined functions in these other
  classes of series.
] <prob:multivariate-series-method>

#problem(base-level: 1, prefix: ())[
  Construct a method for generating functions of two or more variables of
  “mixed” type, especially functions of the form #eq(
    $
      A(w,z)=sum_(n=0)^infinity sum_(m=0)^infinity a_(n m) z^n phi_m (w),
    $,
  ) <eq:generalized-generating-series>
  where $\{phi_m (w)\}_(m=0)^infinity$ is an orthonormal system. The
  coefficients identify such expansions with infinite matrices. On a class where
  matrix composition is defined, for example the row-finite matrices, this
  correspondence transports matrix multiplication to a product of generating
  functions. This product generally differs from pointwise multiplication.
] <prob:generalized-generating-series>

#problem(base-level: 1, prefix: ())[
  When Problems
  @prob:generalized-series-method[]–@prob:generalized-generating-series[] have
  positive solutions, extend the method's uniform approach to finding integral
  representations and evaluating the following sums:

  4.1. sums with $q$-binomial coefficients;

  4.2. sums over partitions;

  4.3. sums over divisors;

  4.4. infinite sums generated by Fourier series;

  4.5. sums of other types.

  Seek new multiple summation formulas and analogues of known power-series
  summation formulas, with particular attention to sums arising directly in
  combinatorial applications.
] <prob:generalized-identities>

#problem(base-level: 1, prefix: ())[
  Write analogues of the integral representations for the general term of a
  $2n$-dimensional matrix of type $F_n^1$ (see §@sec:univariate-inversion) in
  the algebras of series in Problems
  @prob:generalized-series-method[]–@prob:generalized-generating-series[].
  Determine how these matrices are connected with known summation methods for
  divergent series (see, for example, #bib-ref(
    "Hardy1949",
  )) and
  #source(237, "225")
  with known discrete probability distributions. Obtain analogues of the
  decomposition and inversion theorems. Write analogues of the inverse pairs in
  §@sec:univariate-inversion for matrices of type $F_1^1$. Give combinatorial
  interpretations of the results (see, for example, #bib-ref("Good1965"),
  #bib-ref("Chottin1975") and #bib-ref("Tutte1975")).
] <prob:generalized-matrix-inversion>

#problem(base-level: 1, prefix: ())[
  Starting from the integral representations in @th:binomial-parameter-sum and
  @th:binomial-product-sum for sums of the forms @eq:binomial-parameter-sum and
  @eq:binomial-product-sum, find conditions on the free parameters under which
  these sums can be evaluated in closed form.

  Problems @prob:regular-summation-methods[] and
  @prob:multivariate-summation-kernel[] concern probabilistic properties of
  matrices of type $F_n^1$.
] <prob:closed-form-sum-classification>

#problem(base-level: 1, prefix: ())[
  Find conditions on the numerical sequences $\{alpha_m\}_(m=0)^infinity$ and
  $\{beta_k\}_(k=0)^infinity$ and the analytic functions $g(w)$, $f_1 (w)$ and
  $psi_1 (w)$ under which a matrix of type $F_1^1$ is: a) stochastic; b) doubly
  stochastic. Find multidimensional analogues for matrices of type $F_n^1$.
] <prob:regular-summation-methods>

#remark[
  For an infinite row-stochastic matrix $(C_(m n))$, the associated linear
  summation method is regular, that is, preserves the limits of convergent
  sequences, if and only if $C_(m n)->0$ as $m->infinity$ for each fixed $n$.
  Nonnegativity and unit row sums alone do not imply regularity.

  Matrices of type $F_1^1$ include Gronwall's summation matrices, which give
  many regular summation methods under suitable additional analytic conditions.
  The Gronwall matrix acts on the partial sums of a series and is lower
  triangular, with general term #eq(
    $
      C_(m n) & =res_w (g(w) f(w)^n (1-f(w)))/(b_m w^(m+1)) \
              & =1/(2 pi i b_m) integral_(abs(w)=rho)
                (g(w) f(w)^n (1-f(w)))/(w^(m+1)) dif w,
    $,
  ) <eq:summation-matrix-kernel>
  #index-mark([@eq:summation-matrix-kernel], group: [Methods])[Gronwall
    summation]
  where $m,n=0,1,2,dots$, $g(w)=sum_(m=0)^infinity b_m w^m$, $b_m!=0$ for all
  $m$, $f(0)=0$ and $f'(0)!=0$. The positively oriented circle lies in a disk
  where $f$ and $g$ are holomorphic.

  A. A. Melentsov's Doctoral Dissertation (Scientific Library, Ural State
  University, Sverdlovsk) investigates this method and its generalizations for
  $n=1$, starting from the properties of the holomorphic functions $f$ and $g$.
]

#problem(base-level: 1, prefix: ())[
  Suppose that a matrix of type $F_n^1$ is given (see @def:matrix-integral).
  Write $m=(m_1,dots,m_n)$ and $k=(k_1,dots,k_n)$. Let $g(w)$,
  $f_1 (w),dots,f_n (w)$ and $psi_1 (w),dots,psi_n (w)$ be holomorphic in a
  neighbourhood of the closure of a polydisk $U(rho)$ with skeleton
  $
    Gamma(rho)=\{w in CC^n: abs(w_j)=rho_j, quad j=1,dots,n\}.
  $
  #source(238, "226")
  Associated with this matrix are the numerical sequences $\{p(m)\}$ and
  $\{q(k)\}$:

  #keep-next[a) $p(m)=p(m_1,dots,m_n)$:]
  #eq(
    $
      p(m) & =1/((2 pi i)^n beta_k) integral_(Gamma(rho)) g(w) \
           & quad times product_(j=1)^n
             (f_j (w)^(m_j)(1-f_j (w)) w_j^(-k_j-1)) dif w,
    $,
  ) <eq:multivariate-summation-kernel>
  where $m_1,dots,m_n=0,1,2,dots$, the $k_j$ are fixed positive integers, and
  $abs(f_j (w))<1$ on $Gamma(rho)$ for every $j$.
  $
    beta_k=(2 pi i)^(-n) integral_(Gamma(rho)) g(w) w^(-k-I) dif w != 0.
  $
  Sufficiently small radii give the bound whenever $f_j (0)=0$. Summing the
  geometric series under the integral gives $sum_m p(m)=1$; nonnegativity is a
  further requirement.

  #keep-next[b) $q(k)=q(k_1,dots,k_n)$:]
  #eq(
    $
      q(k)=1/((2 pi i)^n) integral_(Gamma(rho)) g(w)
      product_(j=1)^n (psi_j (w)^(k_j) w_j^(-k_j-1)) dif w,
    $,
  ) <eq:multivariate-transform-kernel>
  where $k_1,dots,k_n=0,1,2,dots$ and $psi_j (0)!=0$ for $j=1,dots,n$. Under
  suitable sufficient conditions on $g$ and the $psi_j$, this sequence defines
  the one-dimensional discrete Lagrange distribution or its multidimensional
  generalization introduced by Consul and Shenton in #bib-ref("Consul1972") and
  #bib-ref("Consul1973"). These families include a number of known discrete
  distributions.
] <prob:multivariate-summation-kernel>

#subproblem[
  Find conditions on $g$ and $f_1,dots,f_n$ under which
  @eq:multivariate-summation-kernel defines a probability distribution.
] <prob:probability-kernels>

#subproblem[
  Find integral, closed-form (if possible), and asymptotic representations for
  the moments of a distribution of the form @eq:multivariate-summation-kernel,
  together with local and integral limit theorems for distributions of the forms
  @eq:multivariate-summation-kernel and @eq:multivariate-transform-kernel. In
  particular, solve these problems for distributions of the form
  @eq:multivariate-summation-kernel obtained from the matrix of the method
  $P(q,r,s)$, which is of type $F_1^1$ (see @prob:summation-relations).
] <prob:distribution-moments>

#problem(base-level: 1, prefix: ())[
  If Problems
  @prob:generalized-series-method[]–@prob:generalized-generating-series[] have
  positive solutions:

  9.1. Answer the questions in Problems @prob:regular-summation-methods[] and
  @prob:multivariate-summation-kernel[].

  9.2. Use the method of integral representation of sums, as in
  §§@sec:unbounded-szego-kernels and @sec:bounded-kernels, to find closed forms
  for kernels of integral representations of holomorphic functions on various
  domains in $CC^n$.

  #source(239, "227")
] <prob:generalized-moment-methods>

#problem(base-level: 1, prefix: ())[
  Find integral representations and closed forms (if possible) for the Fourier
  kernels #bib-ref("Hardy1949") of particular Gronwall summation methods (see
  @prob:summation-relations). Generalize the results to two or more dimensions.
] <prob:fourier-summation-kernels>

#problem(name: [Aizenberg], base-level: 1, prefix: ())[
  Describe the complete $n$-circular domains $D$ and the measures $lambda$ on
  $abs(partial D)$ for which the corresponding Szegő kernels can be expressed in
  closed form.
] <prob:closed-form-szego-kernels>

#problem(name: [Aizenberg], base-level: 1, prefix: ())[
  Describe the complete $n$-circular domains $D$ and the measures $lambda$ on
  $abs(partial D)$ for which the corresponding Szegő kernels are rational.
] <prob:rational-szego-kernels>
